[[redirects]]
  from = "/api/login"
  to = "https://pt-server.pp.ua"
  status = 200
  force = true
headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"